### PR TITLE
Partial lattice building experiment

### PR DESCRIPTION
**Pull request by twalenczyk**
Added code that creates a distribution for a density matrix, samples it poly(log(N)) times, and tries to build the hidden congruence. Though the "experiment" is a bust at the moment, it's moving in the right direction. More visibility would be nice, hence the pull request.

### CODE REVIEW

**Comment by twalenczyk** [comment]
Update: Originally, I tried building an algebra out of sampled elements using subalg_gen (as it is now), but it kept breaking in the single_closure phase. Adding the 'print(list(args_all))' to the single_closure function patched the issue and introduced extremely varied output (not sure if the variety breaks the function or not). So, I recommend not merging this into master until we can reconcile the strange behavior with ualgebra.py.

**Comment by twalenczyk** [comment]
In fact, it's certain that adding that "print" prevent rand_cong from generating valid congruences.

**Comment by notmattmoore** [comment]
list_args is an iterator. Converting it to a list essentially 'empties' the iterator and uses the returned content to form a list. If you want to investigate output, you would probably want to do something like:
  args_all = list(args_all)
  print(args_all)

**Comment by twalenczyk** [comment]
Closing because I'm certainly putting the cart before the horse.

**Pull request closed without merging**
